---
# Default Kibana configuration from kibana-docker.

server.name: kibana
server.host: "0"
server.basePath: "/kibana"
elasticsearch.url: http://elastic:9200
#xpack.monitoring.ui.container.elasticsearch.enabled: true
